<h1><center>Basic Notations (Python/Tensorflow)</center></h1>

### Autor
- Nombre: Edwin Jahir Rueda Rojas
- email: ejrueda95g@gmail.com

### Numpy
- Numpy es la librería (paquete) fundamental en python para computación científica.
- Permite representar vectores, matrices, operaciones entre vectores, matrices, etc.

Referencia [Python:Numpy](https://numpy.org/doc/stable/user/whatisnumpy.html)

In [2]:
import numpy as np

v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

#### Broadcasting
- El broadcasting permite ajustar las dimensiones para poder hacer operaciones entre vectores y matrices

In [3]:
v2 = np.array([2,2,2,2])
print("v1:", v)
print("v2:", v2)
print("v1*v2:", v*v2)

v1: [1 2 3 4]
v2: [2 2 2 2]
v1*v2: [2 4 6 8]


In [4]:
#con broadcastings
v2 = np.array([2])
print("v1:", v)
print("v2:", v2)
print("v1*v2", v*v2)

v1: [1 2 3 4]
v2: [2]
v1*v2 [2 4 6 8]


### Idexación 
- Python indexa desde el valor 0 en adelante.

In [11]:
print("v:",v)
for i in range(len(v)):
    print("v["+str(i)+"]:",v[i])

v: [1 2 3 4]
v[0]: 1
v[1]: 2
v[2]: 3
v[3]: 4


- seleccionar solo un intervalo de índices

In [19]:
vector = np.random.uniform(size=(5))
print("vector:", vector)
print()
print("vector[2:4]:", vector[2:5])
print("vector[1:]:", vector[1:])

vector: [0.63355006 0.90122822 0.91494459 0.31402356 0.44055193]

vector[2:4]: [0.91494459 0.31402356 0.44055193]
vector[1:]: [0.90122822 0.91494459 0.31402356 0.44055193]


In [30]:
# Para invertir el vector
vector[::-1]

array([0.44055193, 0.31402356, 0.91494459, 0.90122822, 0.63355006])

In [34]:
#para seleccionar el índice del número mas grande en el vector
max_index = np.argmax(vector)
print("vector:", vector)
print("índice:", max_index)
print("<< número:", vector[max_index])

vector: [0.63355006 0.90122822 0.91494459 0.31402356 0.44055193]
índice: 2
<< número: 0.914944592709649


### Tensorflow
- Tensorflow implementa tensores, los cuales pueden ser multidimensionales. (son muy semejantes a los arrays de numpy)
    - Variables
    - Constantes

- Lo tensores se enumeran en base a su <b>Rank</b>
    - Rank 0: Es un escalar, no tiene dimensiones.
    - Rank 1: Vector de una dimensión.
    - Rank 2: Matrix con dos o más dimensiones
    
Nota: Tensorflow también cuenta con <b>broadcasting</b>
    
Referencias [Tensorflow:Tensores](https://www.tensorflow.org/guide/tensor)

In [68]:
import tensorflow as tf

t1 = tf.Variable([1,6,2,4])
print("Tensor:", t1)
print("Array:", t1.numpy())
print("Tensor*2:", t1*2)

Tensor: <tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 6, 2, 4], dtype=int32)>
Array: [1 6 2 4]
Tensor*2: tf.Tensor([ 2 12  4  8], shape=(4,), dtype=int32)


- Cuando se entrenan algoritmos con tensorflow avanzado, se tiene que trabajar siempre con tensores, si se mezclan tensores y arrays de numpy, los grafos de tensorflow se vuelven menos eficientes.

In [62]:
t1*tf.constant(2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 2, 12,  4,  8], dtype=int32)>

In [63]:
#indexación
t1[1:3]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 2], dtype=int32)>

In [64]:
#selecciona el índice donde estpa el mayor número
tf.argmax(t1)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [65]:
#devuelve la indexación que ordena el tensor
tf.argsort(t1)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 2, 3, 1], dtype=int32)>